name: Auto Merge PRs

on:
  pull_request:
    types: [labeled, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Checklist
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const checklistRegex = /### ✅ Checklist[\s\S]*?\[x\]\s+🧪 O código foi testado\?\s*\[x\]\s+📝 A documentação foi atualizada\?\s*\[x\]\s+✔️ Todos os testes passam\?/;
            const prBody = context.payload.pull_request.body;

            if (!checklistRegex.test(prBody)) {
              core.setFailed("Checklist não está completo! Todos os itens devem ser marcados com [x].");
            } else {
              console.log("Checklist completo. Prosseguindo com merge...");
            }

      - name: Auto Merge Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash", // Pode ser "merge", "squash" ou "rebase"
            });
